### ISSUE TITLE
No recipe for final collector necklace or final power flower charm

### ISSUE THREAD

**Issue by DarkIlluminatus** [JPANv2/EMCBaubles#6]
As in the title, there is no recipe for the final collector necklace and final power flower charm. Using the most current version of the mod.

**Comment by JPANv2** [comment]
I wasn't meaning to do it (that's why the final necklace and charm didn't even work as curios), but I ended up fixing its bugs and adding a new , expensive recipe to craft them. They are different from all others (8 necklaces surrounding a fading matter block for the final necklace, and 5 fading power flowers in a cross with the gold diagonally for the Final power flower).

**Comment by DarkIlluminatus** [comment]
Thank you very much!
