### ISSUE TITLE
kicks me from game

### ISSUE THREAD

**Issue by KhaleesiCat87** [JPANv2/EMCBaubles#7]
the pedestal wont accept the charm and breaking the pedestal kicks me from the server. Is there a fix for this?

**Comment by JPANv2** [comment]
This was caused by a bug that resulted from not checking properly for server-only functions, when EMC is mostly client-based. Also, I didn't even test on server before because I mainly only use "Open to LAN", but not the full mod has been tested and is mostly server safe (just don't try to erase or replace blocks in over 64 chunks like my brother did).
